# Generated by Django 4.2.9 on 2025-05-20
from django.db import migrations
import csv
from pathlib import Path

def load_user_data(apps, schema_editor):
    User = apps.get_model('account', 'User')

    csv_path = Path(__file__).resolve().parent / 'csv' / 'account_user.csv'
    with open(csv_path, newline='', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            User.objects.update_or_create(
                id=row['id'],
                defaults={
                    'email': row['email'],
                    'name': row['name'],
                    'com_number': row['com_num'],
                    'is_active': row['is_active'] == '1',
                    'is_staff': row['is_staff'] == '1',
                    'is_superuser': row['is_superuser'] == '1',
                    'terms_accepted': row['tc'] == '1',
                    'password': row['password'],  # already hashed
                }
            )
            print(f"✅ Inserted User: {row['email']}")

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),  # Update with your actual last migration
    ]

    operations = [
        migrations.RunPython(load_user_data),
    ]
