# Generated by Django 4.2.9 on 2025-05-20
from django.db import migrations
import csv
from pathlib import Path

def load_user_profile_data(apps, schema_editor):
    UserProfile = apps.get_model('account', 'UserProfile')
    User = apps.get_model('account', 'User')

    csv_path = Path(__file__).resolve().parent / 'csv' / 'account_profile.csv'
    with open(csv_path, newline='', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            try:
                user = User.objects.get(id=row['user_id'])
                UserProfile.objects.update_or_create(
                    id=row['id'],
                    defaults={
                        'height': row['height'] or '',
                        'weight': row['weight'] or '',
                        'gender': row['gender'] or '',
                        'age': row['age'] or '',
                        'user': user,
                    }
                )
                print(f"✅ Inserted profile for user ID: {row['user_id']}")
            except User.DoesNotExist:
                print(f"❌ Skipped: User ID {row['user_id']} does not exist")
                continue

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_init_migration'),  # Update to your latest migration
    ]

    operations = [
        migrations.RunPython(load_user_profile_data),
    ]
