# Generated by Django 4.2.9 on 2025-05-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.CharField(max_length=20)),
                ("event", models.CharField(max_length=25)),
                ("accel_x", models.CharField(max_length=20)),
                ("accel_y", models.CharField(max_length=20)),
                ("accel_z", models.CharField(max_length=20)),
                ("gyro_x", models.CharField(max_length=20)),
                ("gyro_y", models.CharField(max_length=20)),
                ("gyro_z", models.CharField(max_length=20)),
                ("mag_x", models.CharField(max_length=20)),
                ("mag_y", models.CharField(max_length=20)),
                ("mag_z", models.CharField(max_length=20)),
                ("latitude", models.CharField(max_length=20)),
                ("longitude", models.CharField(max_length=20)),
                ("pressure", models.CharField(max_length=20)),
                ("speed", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Sensor Insight",
                "verbose_name_plural": "Sensor Insights",
                "db_table": "device_sensor_data",
            },
        ),
        migrations.CreateModel(
            name="SessionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("start_timestamp", models.BigIntegerField()),
                ("end_timestamp", models.BigIntegerField()),
                ("steps_taken", models.IntegerField(default=0)),
                ("wheelchair_id", models.IntegerField()),
                ("start_quality_1", models.CharField(default="0", max_length=10)),
                ("start_quality_2", models.CharField(default="0", max_length=10)),
                ("start_quality_3", models.CharField(default="0", max_length=10)),
                ("end_quality_1", models.CharField(default="0", max_length=10)),
                ("end_quality_2", models.CharField(default="0", max_length=10)),
                ("version", models.CharField(default="old", max_length=20)),
                ("duration_ms", models.BigIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Device Session Data",
                "verbose_name_plural": "Device Session Data",
                "db_table": "device_session_data",
            },
        ),
    ]
