# Generated by Django 4.2.9 on 2025-05-27 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0004_sensordata_session_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensordata",
            name="session_id",
        ),
        migrations.AddField(
            model_name="sensordata",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sensors",
                to="device.sessiondata",
            ),
        ),
    ]
