# Generated by Django 4.2.9 on 2025-05-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WheelchairDriveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "WheelchairDriveType",
                "verbose_name_plural": "WheelchairDriveType",
                "db_table": "wheelchair_drive_type",
            },
        ),
        migrations.CreateModel(
            name="WheelchairTireMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "WheelchairTireMaterial",
                "verbose_name_plural": "WheelchairTireMaterial",
                "db_table": "wheelchair_tire_material",
            },
        ),
        migrations.CreateModel(
            name="WheelchairType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "WheelchairType",
                "verbose_name_plural": "WheelchairsType",
                "db_table": "wheelchair_type",
            },
        ),
    ]
